export {default as Home} from './home/Home'
export {default as Planets} from './planets/Planets'
export {default as Species} from './species/Species'
export {default as Vehicles} from './vehicles/Vehicles'
export {default as Starships} from './starships/Starships'